### ISSUE TITLE
plugin stable diffusion 

### ISSUE THREAD

**Issue by redclif43** [ShirokamiRyzen/Nao-MD#1]
bang tambahin plugin stable diffusion dong pake api dari huggingface

**Comment by redclif43** [comment]
ditunggu bang , biar pake access token sama api sendiri

**Comment by Zeltoria** [comment]
Api Dapid Aja Om Gratis

**Comment by redclif43** [comment]
> Api Dapid Aja Om Gratis

mana nyoba om web nya ?

**Comment by Zeltoria** [comment]
> > Api Dapid Aja Om Gratis
> 
> mana nyoba om web nya ?

Nih Om
Kalau Regis Apikeynya Ada Di GCnya Cek Aja Di webnya
https://api.itsrose.site
