### ISSUE TITLE
[Known Issue] Pairing code does not appear on some terminals

### ISSUE THREAD

**Issue by ShirokamiRyzen** [ShirokamiRyzen/Nao-MD#10]
In some terminals such as pterodactyl the pairing code does not appear, and this is a temporary way to retrieve the pairing code. see video (because github can only upload media of 10mb, I put the video on the link)

[troubleshoot](https://cloud.ryzendesu.com/id/Media/video/etc/2023-09-21%2013-44-54.mp4)

**Comment by ju-ma-tech** [comment]
session can't find

**Comment by Prince4t7** [comment]
Qr code or pairing code not working well

**Comment by Prince4t7** [comment]
Qr code and pairing code not working well

**Comment by ShirokamiRyzen** [comment]
Look at the video

**Comment by ShirokamiRyzen** [comment]
> Qr code or pairing code not working well

Nope, this is working as well

**Comment by Hxzz1** [comment]
Where the video? The troubleshoot redirect me to another website

**Comment by Tanjiro2130K** [comment]
Can I host on termux video tutorial pls

**Comment by ShirokamiRyzen** [comment]
> Can I host on termux video tutorial pls

No
