### ISSUE TITLE
cheerio error

### ISSUE THREAD

**Issue by DUCKTys** [ShirokamiRyzen/Nao-MD#22]
cheerio kenapa error ngap, cheerio di modul @bochilteam/scraper juga error

**Comment by ShirokamiRyzen** [comment]
> cheerio kenapa error ngap, cheerio di modul @bochilteam/scraper juga error

hoax

**Comment by DUCKTys** [comment]
> > cheerio kenapa error ngap, cheerio di modul @bochilteam/scraper juga error
> 
> hoax

Tak coba run gk bisa jir di panel
