### ISSUE TITLE
tidak merespon masukan dari wa web

### ISSUE THREAD

**Issue by Xunnli** [ShirokamiRyzen/Nao-MD#25]
![image](https://github.com/user-attachments/assets/53e218fa-9a1a-451b-b750-8dd18e1a2184)

**Comment by ShirokamiRyzen** [comment]
![{FA09CAEB-9414-4F69-B4D1-A58196634F0E}](https://github.com/user-attachments/assets/d854ddc3-5b22-4aa1-9bff-1318d981f81f)
Mana?

**Comment by Xunnli** [comment]
nih bang

https://github.com/user-attachments/assets/ec88e20b-3c95-4957-b4c2-6087391b4f33
