### ISSUE TITLE
.addprem error

### ISSUE THREAD

**Issue by cangka22** [ShirokamiRyzen/Nao-MD#4]
.addprem error bang ryzen

**Comment by ShirokamiRyzen** [comment]
no issue

![image](https://user-images.githubusercontent.com/76462435/231452805-da663f27-0bf1-4547-ba94-51cd7c7754aa.png)

**Comment by ShirokamiRyzen** [comment]
No issue, jangan lupa ubah nomer owner 

![photo_2023-04-12_19-10-37](https://user-images.githubusercontent.com/76462435/231453289-f52b9e90-d10b-4f75-b6b2-c2564ee0d8ba.jpg)

**Comment by cangka22** [comment]
Fix bang ryzen makasih
