### ISSUE TITLE
ENOENT  No such file directory

### ISSUE THREAD

**Issue by NoobsMaster699** [ShirokamiRyzen/Nao-MD#6]
If typing the .menu command an error like this will appear

[Error: ENOENT: no such file or directory, open '-'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '-'
}
Plugin: main-menuawal.js

**Comment by ShirokamiRyzen** [comment]
Use `.cleartmp` to reset folder permission if u using pterodactyl
